name: Update GitHub Stats

on:
  schedule:
    - cron: "* * * * *"  # updates every hour (adjust as needed)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Hardek00
          include_all_commits: true
          count_private: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
